# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
 
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
 
default_platform(:ios)
 
platform :ios do
  desc "Description of what the lane does"
  lane :CI do
      run_tests(project: "TruthOrDare.xcodeproj",
      devices: ["iPhone 8"],
      scheme: "TruthOrDare")
  end
 
  lane :CD do |values|
 
    gym(scheme: 'TruthOrDare', project: "TruthOrDare.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')
 
    emails = values[:akshay.band@goqii.com] ? values[:test_email] : ['[email]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
    crashlytics(api_token: '[AIzaSyCQPjL-jFToblnmKp0bocibukU5UFWLrfI]',
             build_secret: '[624371676021-3if9mt7spji7gsfkrqg1j2jti59qf9s4.apps.googleusercontent.com]',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
 
    end
end